### ISSUE TITLE
Minor nit in extension name

### ISSUE THREAD

**Issue by jedgrant** [sereneinserenade/tiptap-search-and-replace#1]
In the code pulled directly from the repo, as instructed in the readme, it appears the extension name should be `SearchAndReplace` but in the Readme, it references a `SearchNReplace` name instead. Mildly confusing, just a documentation consideration. Thanks for making the extension!

**Comment by sereneinserenade** [comment]
Thanks @jedgrant !

Fixed, published it to npm and it'd export `SearchAndReplace` 😄
