### ISSUE TITLE
Feature Request - add previous and next buttons

### ISSUE THREAD

**Issue by alexbennycodes** [sereneinserenade/tiptap-search-and-replace#3]
![image](https://github.com/sereneinserenade/tiptap-search-and-replace/assets/98402835/65832db8-8d63-42c0-83b4-0cba2e62e98c)
 Is there a possibility that this feature could be implemented which allows user to move to the next and previous occurance?

**Comment by sereneinserenade** [comment]
implemented with https://github.com/sereneinserenade/tiptap-search-and-replace/releases/tag/v0.1.0

**Comment by sereneinserenade** [comment]
demo: https://sereneinserenade.github.io/tiptap-search-and-replace/
